events {}

http {
  server {
    listen 80;

    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location /api/ {
      proxy_pass http://backend:8080/api/;
    }

    location /api/track/ {
        auth_basic off;
        proxy_pass http://backend:8080/api/track/;
    }

    location /blocks/ {
      proxy_pass http://letter-constructor:8080/blocks/;
    }

    location /templates/ {
      proxy_pass http://letter-constructor:8080/templates/;
    }

    location / {
      proxy_pass http://frontend:80/;
    }
  }
}